### ISSUE TITLE
Critical: WebRTC IP Leak

### ISSUE THREAD

**Issue by r3v3rs3** [guardianproject/Orweb#69]
Critical leak of IP information using WebRTC RTCpeerconnection.
When JavaScript is enabled the browser allows for direct peer connections to ICE server that reveals the real user IP address.

**Comment by n8fr8** [comment]
Stop using Orweb, start using Orfox:
https://guardianproject.info/2015/06/30/orfox-aspiring-to-bring-tor-browser-to-android/

**Comment by amoghbl1** [comment]
@n8fr8 : I think updating the readme with that might help in the future?

**Comment by n8fr8** [comment]
Try @amoghbl1 is does say it on the main project page:
We are EOL this project. Please use Lightning Browser or wait for Orfox instead https://dev.guardianproject.info/projects/orfox-private-browser  

I wish there was a way on Github to "archive" a project.
